import {Router} from "express";import {z} from "zod";import {requireAuth} from "../middleware/auth.js";import {requireMember} from "../lib/business.js";
const r=Router(); const ctx=(req:any)=>({client:req.auth.client,userId:req.auth.userId,businessId:req.params.businessId});
async function guard(req:any){const c=ctx(req);await requireMember(c.client,c.userId,c.businessId);return c;}
r.get("/products",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("products").select("*").eq("business_id",c.businessId);if(error)throw error;res.json({products:data??[]});}catch(e){next(e);}});
r.post("/products",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({name:z.string().min(1),description:z.string().optional(),category:z.string().optional(),price:z.number().nonnegative(),cost:z.number().nonnegative().default(0),stock:z.number().int().nonnegative().default(0),low_stock_threshold:z.number().int().nonnegative().default(0),aliases:z.array(z.string()).default([])}).parse(req.body);const {data,error}=await c.client.from("products").insert({...b,business_id:c.businessId}).select("*").single();if(error)throw error;res.status(201).json({product:data});}catch(e){next(e);}});
r.get("/customers",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("customers").select("*").eq("business_id",c.businessId);if(error)throw error;res.json({customers:data??[]});}catch(e){next(e);}});
r.post("/customers",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({name:z.string().min(1),phone:z.string().optional(),email:z.string().email().optional(),address:z.string().optional()}).parse(req.body);const {data,error}=await c.client.from("customers").insert({...b,business_id:c.businessId}).select("*").single();if(error)throw error;res.status(201).json({customer:data});}catch(e){next(e);}});
r.get("/orders",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("orders").select("*").eq("business_id",c.businessId).order("created_at",{ascending:false});if(error)throw error;res.json({orders:data??[]});}catch(e){next(e);}});
r.post("/orders",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({customer_id:z.string().uuid().nullable().optional(),subtotal:z.number().nonnegative(),discount:z.number().nonnegative().default(0),total:z.number().nonnegative(),items:z.array(z.object({product_id:z.string().uuid(),quantity:z.number().int().positive(),unit_price:z.number().nonnegative()}))}).parse(req.body);const {data,error}=await c.client.rpc("create_order_safe",{p_business_id:c.businessId,p_customer_id:b.customer_id??null,p_subtotal:b.subtotal,p_discount:b.discount,p_total:b.total,p_items:b.items});if(error)throw error;res.status(201).json({order:data});}catch(e){next(e);}});
r.get("/inventory",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("products").select("product_id,name,stock,low_stock_threshold,price,cost").eq("business_id",c.businessId);if(error)throw error;res.json({inventory:data??[]});}catch(e){next(e);}});
r.post("/inventory/transactions",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({product_id:z.string().uuid(),delta:z.number().int().refine(v=>v!==0),reason:z.string().min(1),reference:z.string().optional()}).parse(req.body);const {data,error}=await c.client.rpc("apply_inventory_transaction",{p_business_id:c.businessId,p_product_id:b.product_id,p_delta:b.delta,p_reason:b.reason,p_reference:b.reference??null});if(error)throw error;res.status(201).json({transaction:data});}catch(e){next(e);}});
r.get("/invoices",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("invoices").select("*").eq("business_id",c.businessId);if(error)throw error;res.json({invoices:data??[]});}catch(e){next(e);}});
r.post("/invoices",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({customer_id:z.string().uuid().nullable().optional(),order_id:z.string().uuid().nullable().optional(),amount:z.number().nonnegative(),status:z.enum(["unpaid","partially_paid","paid","refunded"]).default("unpaid"),due_date:z.string().optional()}).parse(req.body);const {data,error}=await c.client.from("invoices").insert({...b,business_id:c.businessId}).select("*").single();if(error)throw error;res.status(201).json({invoice:data});}catch(e){next(e);}});
r.get("/payments",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const {data,error}=await c.client.from("payments").select("*").eq("business_id",c.businessId);if(error)throw error;res.json({payments:data??[]});}catch(e){next(e);}});
r.post("/payments",requireAuth,async(req,res,next)=>{try{const c=await guard(req);const b=z.object({customer_id:z.string().uuid().nullable().optional(),order_id:z.string().uuid().nullable().optional(),invoice_id:z.string().uuid().nullable().optional(),amount:z.number().positive(),method:z.string().min(1),reference:z.string().optional()}).parse(req.body);const {data,error}=await c.client.from("payments").insert({...b,business_id:c.businessId,status:"confirmed"}).select("*").single();if(error)throw error;res.status(201).json({payment:data});}catch(e){next(e);}});
export default r;
