create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','admin','staff');
create type public.order_status as enum ('pending','confirmed','processing','ready','completed','cancelled');
create type public.payment_status as enum ('unpaid','partially_paid','paid','refunded');
create type public.autonomy_level as enum ('assisted','approval','controlled');

create table public.businesses(business_id uuid primary key default gen_random_uuid(),name text not null,owner_user_id uuid not null references auth.users(id) on delete restrict,category text,country text not null default 'Cameroon',city text,currency text not null default 'XAF',goals jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.business_members(business_id uuid references public.businesses on delete cascade,user_id uuid references auth.users on delete cascade,role public.member_role not null default 'staff',full_name text,phone text,created_at timestamptz not null default now(),primary key(business_id,user_id));
create table public.products(product_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,name text not null,description text,category text,price numeric(18,2) not null check(price>=0),cost numeric(18,2) not null default 0 check(cost>=0),stock integer not null default 0 check(stock>=0),low_stock_threshold integer not null default 0 check(low_stock_threshold>=0),aliases jsonb not null default '[]',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customers(customer_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,name text not null,phone text,email text,address text,total_orders integer not null default 0,total_spent numeric(18,2) not null default 0,outstanding numeric(18,2) not null default 0,last_order_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(order_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,customer_id uuid references public.customers on delete set null,status public.order_status not null default 'pending',payment_status public.payment_status not null default 'unpaid',subtotal numeric(18,2) not null check(subtotal>=0),discount numeric(18,2) not null default 0,total numeric(18,2) not null check(total>=0),items jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.invoices(invoice_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,customer_id uuid references public.customers on delete set null,order_id uuid references public.orders on delete set null,amount numeric(18,2) not null check(amount>=0),status public.payment_status not null default 'unpaid',due_date date,created_at timestamptz not null default now());
create table public.payments(payment_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,customer_id uuid references public.customers on delete set null,order_id uuid references public.orders on delete set null,invoice_id uuid references public.invoices on delete set null,amount numeric(18,2) not null check(amount>0),method text not null,reference text,status text not null default 'confirmed',created_at timestamptz not null default now());
create table public.inventory_transactions(transaction_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,product_id uuid not null references public.products on delete cascade,delta integer not null check(delta<>0),reason text not null,reference text,created_at timestamptz not null default now());
create table public.activity_logs(activity_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,actor_user_id uuid references auth.users on delete set null,action_type text not null,affected_record text,previous_value jsonb,new_value jsonb,status text not null,created_at timestamptz not null default now());
create table public.koda_memory(memory_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,key text not null,value jsonb not null,updated_at timestamptz not null default now(),unique(business_id,key));
create table public.koda_settings(business_id uuid primary key references public.businesses on delete cascade,autonomy_level public.autonomy_level not null default 'assisted',paused boolean not null default false,updated_at timestamptz not null default now());
create table public.koda_permissions(business_id uuid references public.businesses on delete cascade,action_type text not null,allowed_risk_level text not null default 'low',created_at timestamptz not null default now(),primary key(business_id,action_type));
create table public.koda_tasks(task_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,title text not null,priority text not null default 'medium',source text,done boolean not null default false,created_at timestamptz not null default now());
create table public.koda_alerts(alert_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,message text not null,severity text not null default 'info',created_at timestamptz not null default now());
create table public.koda_goals(goal_id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,label text not null,target numeric(18,2) not null default 0,progress numeric(18,2) not null default 0,period text,created_at timestamptz not null default now());
create table public.subscriptions(subscription_id uuid primary key default gen_random_uuid(),business_id uuid unique not null references public.businesses on delete cascade,plan text not null default 'starter',status text not null default 'trial',renews_at timestamptz,provider text,provider_reference text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create or replace function public.is_business_member(b uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.business_members m where m.business_id=b and m.user_id=auth.uid());$$;

do $$ declare t text; begin
foreach t in array array['business_members','products','customers','orders','invoices','payments','inventory_transactions','activity_logs','koda_memory','koda_settings','koda_permissions','koda_tasks','koda_alerts','koda_goals','subscriptions'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy business_members_select on public.business_members for select using(user_id=auth.uid() or public.is_business_member(business_id));
create policy businesses_select on public.businesses for select using(owner_user_id=auth.uid() or public.is_business_member(business_id));
create policy businesses_update on public.businesses for update using(owner_user_id=auth.uid()) with check(owner_user_id=auth.uid());
create policy products_access on public.products for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy customers_access on public.customers for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy orders_access on public.orders for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy invoices_access on public.invoices for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy payments_access on public.payments for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy inventory_access on public.inventory_transactions for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy activity_select on public.activity_logs for select using(public.is_business_member(business_id));
create policy activity_insert on public.activity_logs for insert with check(public.is_business_member(business_id));
create policy koda_memory_access on public.koda_memory for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy koda_settings_access on public.koda_settings for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy koda_permissions_access on public.koda_permissions for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy koda_tasks_access on public.koda_tasks for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy koda_alerts_access on public.koda_alerts for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy koda_goals_access on public.koda_goals for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));
create policy subscriptions_access on public.subscriptions for all using(public.is_business_member(business_id)) with check(public.is_business_member(business_id));

create or replace function public.create_business_for_current_user(p_name text,p_category text,p_country text,p_city text,p_currency text,p_goals jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare b uuid;begin if auth.uid() is null then raise exception 'not_authenticated';end if;insert into public.businesses(name,owner_user_id,category,country,city,currency,goals) values(p_name,auth.uid(),p_category,coalesce(p_country,'Cameroon'),p_city,coalesce(p_currency,'XAF'),coalesce(p_goals,'[]')) returning business_id into b;insert into public.business_members(business_id,user_id,role) values(b,auth.uid(),'owner');insert into public.koda_settings(business_id) values(b);insert into public.subscriptions(business_id,plan,status) values(b,'starter','trial');return b;end;$$;
